---
title: "Revisiting Goodhart's Law - Net Zero"
#description: "blog post description (appears underneath the title in smaller text) which is included on the listing page"
author:
  - name: Aryamik Sharma
    url: https://aryamik.github.io
date: 11-31-2024
categories: 
- Sustainability
- Philosophy

# self-defined categories

draft: false # setting this to `true` will prevent your post from appearing on your listing page until you're ready!
editor: 
  markdown: 
    wrap: 72
---

<https://www.bloomberg.com/news/articles/2024-05-08/the-fraught-process-of-measuring-bank-climate-progress>

<https://www.bloomberg.com/news/articles/2024-07-24/the-accounting-flaw-at-the-heart-of-financed-emissions?srnd=undefined>

Riddle me this:

I can't be bought, nor can I be sold,\
I’m found in moments, both young and old.\
I grow when shared, but shrink when hoarded,\
I bring warmth when your heart’s unguarded.\
What am I?

If you guessed happiness, you are right. To be fair, the first line
('can't be bought') gave it away. But in any event., since the dawn of
time,

Ask any random person walking on the street what do they want, almost
all of them would want something that directly or indirectly leads to
happiness.

So why am I bringing up the idea of happiness in a time where
devastating wildfires have engulfed parts of LA.

All the more reason to protecvt.

Goping back to ENV 195 in my first year at UW, we learned of all the
reasons to value nature.

anthropocentric values . We can't really put a price on nature. H

So is seeking awe the cure to all our problems? Most likely, not. All we
can say is nature is still the best mediums to find these opportunities
of being awe struck. While it may evade us on daily basis,

Another reason to look after nature.

Another perspective of nature conservation. Those instrinc or
'ornamental' values.

Everyone has been talking about

I finished reading ''Phosphorescence: A Memoir of Finding Joy When Your
World Goes Dark''. As the title suggests, the premise of the book is how
can we become phosphorescence - that is finding those night creatures

One of the things that piqued my interest was the importance of 'awe'.

being awe struck. When was the last time. I urge you to think about when
was the last time you were awestruck. Now that's a word When I aksed
myself, the closed thing I could think of was when I was out on trip
with my buddies in Lansdowne, Uttarakhand in January 2021. I remember,
one the last night of our trip, we were all busy having a good time on
the rooftops of our hotel. And it was a perfect starry night.

i will let you be the judge of it.

We just sat there for hours, and were starstruck at what we were all
seeing.

Years of light pollution and living in 400 AQI riddled New Delhi had
made us lose sight of something that is literally right above every
single night.

One of my bucket list items is to observe the white 'streak' of Milky
Way you get to witness. Keck observatory in Hawaii or Grand Canyon.

We get to be mesmerized and see we are bigger than who we are.

Later this week, I was hearing to Huberman Lab's podcast of

```{=html}
<iframe width="560" height="315" src="https://youtu.be/Phm-Alz1Zjo?t=9873" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
```

regularly seeking moments of awe

So imagine my reaction on how I felt when my brother told me he
canvassed 20 national parks last year across Alaska, Texas.

I often wonder what would our world be if we had views like this. If we
thought about it everytime we looked up the sky and instead of seeing
bright neon, we would realize we are all connected and could scale back
on what we are doing

Scottish Highlands. A place in my bucketlist.

The key takeaway is . we don't need to ., Finding moments to be awe
struck in our daily lives is possible. It just happens that nature is
the best medium.

BRian Cox alluded to this feeling of being star struck . It puts things
into perspective.

> **Doomers** are people who are extremely pessimistic or fatalistic
> about global problems such as overpopulation, peak oil, climate
> change, ecological overshoot, pollution, nuclear weapons, and runaway
> artificial intelligence. The term, and its associated term
> **doomerism**, arose primarily on social media. Some doomers believe
> these problems may lead to human extinction.

Let us look at some of the key headlines that may have fueled the
doomerism movement:

-   [2024 was the warmest year in the history](https://archive.ph/nTebO)

-   [UN Says World Is Now on Course for Warming of Up to
    3.1C](https://archive.ph/jNUIR)

-   [Earth has overshot its planetary
    boundaries](https://www.thelancet.com/journals/lanplh/article/PIIS2542-5196(24)00042-1/fulltext)

-   [A devastating hurricane season in the
    Atlantic](https://archive.ph/JF3xZ)

-   [Record heatwaves in Southeast
    Asia](https://www.worldweatherattribution.org/climate-change-made-the-deadly-heatwaves-that-hit-millions-of-highly-vulnerable-people-across-asia-more-frequent-and-extreme/)

-   [Floods in
    Valencia](https://www.theguardian.com/artanddesign/2024/nov/29/floods-in-valencia-spain-then-and-now-in-pictures)

-   [Rise in Anti-ESG sentiment](https://archive.ph/U14NU)

-   [An underwhelming COP 29](https://archive.ph/ePFy4)

```{=html}
<p align = 'center'><iframe src="" width="480" height="360" style="https://youtu.be/Phm-Alz1Zjo?t=9873" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/reaction-xBqg5gAf1xINizpek6">via GIPHY</a></p>
```

I was curious to examine the root cause of what fuels doomerism. My
immediate reaction was 'social media'. And there is growing evidence to
support this. Work by [Jonathan
Haidt](https://jonathanhaidt.com/social-media/) does indicate that
social media has played a major role in increased polarization we are
currently witnessing.

But social media can't be the cause of all evil, can it? Going back to
the definition of doomerism, it is marked by having an extremely
pessimistic or fatalistic view about the future; a feeling of dread,
nihilism and anxiety. Yes, social media can exacerbate these feelings
but the underlying idea behind doomerism is that no matter what we do;
no matter how many EVs I drive, how many Solar Panels I install at my
home, how many trees I plant - none of it matters in the grand scheme of
things.

To put this into perspective, consider this statement I first came
across in [Kurzgesagt's *What Can You do to Stop Climate Change? And
Should You?*](https://sites.google.com/view/sources-climate-how/)

> **If you eliminated 100% of your emissions for the rest of your life,
> you would save one second’s worth of emissions from the global energy
> sector.**

This dwarves in comparison to the global emissions and even the most
motivated person can't make a tiny dent. One can feel like Sisyphus who
is doomed to push the rock forever.

In *The Meaning of Anxiety*, Rollo May asserts that anxiety serves a
purpose. Traditionally, the purpose was to protect us from primitive
dangers. However, in the modern society, the purpose is to protect us
from from dangers that threaten our existence or values that we identify
with. In other words, anxiety is our human awareness of the fact that
each of us is a *being confronted with nonbeing*. Nonbeing is that which
would destroy being, such as death, severe illness, interpersonal
hostility, too sudden change which destroys our psychological
rootedness.

May concludes that we can temporarily alleviate our anxiety by shielding
ourselves and ignoring the problem causing the anxiety. But that comes
at a price of our human potential, our selfhood, our creativity. In
other words we are stifling ourselves to alleviate this anxiety and
therefore *the positive aspects of selfhood develop as the individual
confronts, moves through, and overcomes anxiety-creating experiences.*

Kierkegaard describes this eloquently in *The Sickness Unto Death:*

> So it is too that in the eyes of the world it is dangerous to venture.
> And why? Because one may lose. But not to venture is shrewd. And yet,
> by not venturing, it is so dreadfully easy to lose that which it would
> be difficult to lose in even the most venturesome venture, and in any
> case never so easily, so completely as if it were nothing—one’s self.
> For if I have ventured amiss—very well, then life helps me by its
> punishment. But if I have not ventured at all—who then helps me? And,
> moreover, if by not venturing at all in the highest sense (and to
> venture in the highest sense is precisely to become conscious of
> oneself) I have gained all earthly advantages . . . and lose my self!
> What of that?

No wonder Kierkegaard called anxiety a better teacher than reality, for
while reality situations may be temporarily evaded, anxiety is an inner
function which cannot be escaped short of constriction of the
personality. It is a signal that something is wrong in one’s personality
and one’s human relationships. It may be viewed as an inward cry for the
resolution of the problem. However, it is this inward cry that has
inspired us to create works of art, poetry, drama, science and other
expressions of human civilization. It is the same inward cry that made
these following events possible in 2024:

-   [Per Capita CO2 Emissions Have Peaked
    Globally](https://ourworldindata.org/data-insights/per-capita-co2-emissions-have-peaked-globally-but-total-emissions-are-still-increasing)

-   [Land set aside for nature is
    increasing.](https://humanprogress.org/trends/more-land-for-nature/)

-   [Support for nuclear energy is
    increasing.](https://www.pewresearch.org/short-reads/2024/08/05/majority-of-americans-support-more-nuclear-power-in-the-country/)

-   Many beloved animal species including [sea
    turtles](https://pmc.ncbi.nlm.nih.gov/articles/PMC10960059/#sec3),
    [Iberian lynx
    wildcat](https://iucn.org/press-release/202406/iberian-lynx-rebounding-thanks-conservation-action-iucn-red-list),
    and [the red-cockaded
    woodpecker](https://www.fws.gov/press-release/2024-10/downlisting-red-cockaded-woodpecker-endangered-threatened)
    whose numbers were dwindling are making a comeback.

That's the thing about doomerism - not only does it stifle our
potential, it also makes us lose sight of the good stuff that is
happening around us.

To wrap things up, the idea behind this post was not to say its all
rainbows and sunshine. Yes, times are difficult and concerning. But it's
about cultivating a spirit of 'mindful optimism' that Max Tegmark and
Erik Brynjolfsson talk about in Life 3.0. According to Erik, there are
two kinds of optimism. First there’s the unconditional kind, such as the
positive expectation that the Sun will rise tomorrow morning. Then
there’s what he called “mindful optimism,” which is the expectation that
good things will happen if you plan carefully and work hard for them.

My first encounter with 'Mindful Optimists' was in *Parts Unknown* where
Anthony Bourdain went to areas like Provincetown (dealing with the
aftermath of the opoid crisis), Puerto Rico (Hurricane Maria in 2017),
Libya (decades of civil unrest and diplomatic tensions), Sri Lanka
(aftermaths of the Sri Lankan Civil War), Detroit (economic fallout) and
other areas that were desolate. One of the questions Bourdain asked the
folks living in these areas was

> Where do you see this place in X years?

Almost all the individuals living these areas had one trait in common -
resilience. They had the attitude of rolling up their sleeves and going
to work *knowing very well that things are not looking good currently.*

The ending monologue in the movie *Arrival* perfectly encapsulates this
sentiment:

> Despite knowing the journey and where it leads, I embrace it. And I
> welcome every moment of it.

Cultivating this mindful optimism is something I want to do in 2025 and
I hope we get to see more of that!

Here's to a great 2025!

```{=html}
<p align = 'center'><iframe src="https://giphy.com/embed/BPJmthQ3YRwD6QqcVD" width="480" height="269" style frameBorder="0" class="giphy-embed" allowFullScreen>
</iframe>

<p><a href="https://giphy.com/gifs/HBOMax-hbomax-the-great-gatsby-2013-thegreatgatsbyonhbomax-BPJmthQ3YRwD6QqcVD"via GIPHY</a></p>
```
