---
title: "Bare Beginnings"
#description: "blog post description (appears underneath the title in smaller text) which is included on the listing page"
author:
  - name: Aryamik Sharma
    url: https://aryamik.github.io

date: 07-01-2024
#categories: [Quarto, R, MEDS] # self-defined categories

draft: false # setting this to `true` will prevent your post from appearing on your listing page until you're ready!
---

Hey there!

Welcome to Sympatheia, my very own personal project that I am very excited to share with everyone!

You might be wondering what is this project all about or what does the word Sympatheia mean in the first place?

A couple of years ago when I was reading Meditations by Marcus Aurelius (which is easily one of my favorite books of all time and would highly recommend that you read it atleast once!), I came across this amazing excerpt:

> Meditate often on the interconnectedness and mutual interdependence of all things in the universe. For in a sense, all things are mutually woven together and therefore an affinity for each other - for one thing follows after another according to their tension of movement, their sympathetic stirrings, and the unity of all substance.

Upon further research, I found that the Stoics had a word for it - sympatheia  - a connectedness with the cosmos.

This concept of interconnectedness is something that deeply resonates with me as I really enjoy connecting the dots from various disciplines in my own life.

You could think of Sympatheia as my own *personal* *journal* where I aim to explore the interconnectedness of some of the areas that I am really passionate about such as:

-   ESG and Sustainability

-   Data Science

-   Machine Learning and Artificial Intelligence

-   Philosophy and Ethics

-   Finance and Economics

At the end of the day it is about my own journey as I try to decipher these seemingly complexy topics and they can possibly interact with each other.

So now that you know a little bit about what this project is all about, I hope you are as intrigued and excited as I am. Your comments, feedback, and suggestions are invaluable to me, so feel free to share them. Stay tuned for more insights and updates!
