---
title: "The Art of Science or The Science of Art"
#description: "blog post description (appears underneath the title in smaller text) which is included on the listing page"
author:
  - name: Aryamik Sharma
    url: https://aryamik.github.io

date: 07-15-2025
categories: 
- AI


draft: true # setting this to `true` will prevent your post from appearing on your listing page until you're ready!
---

The art of science vs the science of art

tThe art of science vs the science of art

AGe old topic

don't worry you are not alone

Da Vinci Sforza court had debates Painting vs statues etc

BAking - Science Cooking - ARt Pizza- Frank Pinollo video Mummy makes her version of food which is amazing and can't be replicated

Exhibhit B BJJ - Danaher's post about martial arts

Educating others on both the positives and negatives of a technology.

How about

But we should be taught about prioritizing human interactions and the negative consequences of spending too much time on these platforms.

Same thing with AI.

?They educa

And the need for moderation above (Once again Virtue Ethics stay winning)

I don't recall seeing

In fact I can see why this was making headlines.

All I am asking for is a nuanced perspective on these narratives. Is it too much to ask?

These were just normal things.

Maybe. Just maybe, this is the logical step in our anthropocentric evolution?

But is it really a bad thing?

I wanted to look at it objectively. Because sensationalism sells

Let me be clear - I am neither pro-technology or anti-technology. And this is by no means a criticism of this amazing study done by Kosmyna and colleagues. In fact, I will talk about why we need more studies like these to better understand the impacts of technological advancements on our overall wellbeing.

My theory is this is because technological change outpaces human evolution. Even though we were able to understand the impacts of social media in the early 2010s, we are seeing laws and regulations on this being drafted in 2025. They can't keep up with the pace at which technology is progressing. In a space, where almost everyday we are seeing a breakthrough, how can we expect to keep up?

Same thing with social media. We should use social media to send funny dog memes to our friends, to learn about exciting stuff happening around us.

Training curricula that include video games may help thin the technical interface between surgeons and screen-mediated applications, such as laparoscopic surgery. Video games may be a practical teaching tool to help train surgeons.

My point is that this is not new.

It's gaining traction now b

And hey we have made blunders in the past. The opposite is whenever a new change came along we accepted it. Smoking and tobacco consumption

Just like almost everything in life.

Virtue Ethics stays winning. Moderation above everything.

What's the saying again? "Dose makes the poison".

Why can't the positives and the negatives

statements can be true at the same time.

It's just like everyth

We value being able to understand each other very well AND we also value being able to write something eloquently. However, problems arise when stuff like ChatGPT gets thrown into the equation and now we have to deal with

These impacts we are witnessing in relation to 'shorter attention spans ' are a byproduct of that.

It's when we start putting labels like 'good' and 'bad' on these effects is where it gets problematic.

Let's take a look at the 'Social media has lowered out attention spans significantly'. The argument is thanks to the 60 second reels, we are having problems with our efficiently. It's having impacts on doing focused work for long periods of time

We value focused work because it results in producing results.

But have we paused to cnosider that maybe this just the direction it is supposed to be? Maybe we are evolving towards a techno-centric future where the is going to different than what we currently know. Maybe we would be communicating telepathically where I would instantly know what you are 'trying to say'.

Yeah is bonoxious and spamming memes in a group chat would probably get you kicked out.

Look at history, language became a thing so that we could communicate with each other.

Language became a means to an end.

So what is wrong if we are communicating with each other over 60 second reels? How is be sending a

No if I were to communicate

AFter all they say a picture is worth a thousand words.

Did I get my point across?

Add to tha

that is being showing no signs of slowing down.

This is what's happening and this is what we should be doing

However, I think we as a society tend to have a knee-jerk reaction towards technological advancements.

This data raises critical questions about how we should balance AI assistance with our cognitive health.

A couple of weeks back, I wrote about this idea of 'technology and laziness'.Essentially the idea that technology is making us lazier is not new.

I am first hand experiencing the effects. In that post, I the inner resistance I have to overcome with.

But why?

Why are we so adamant? Why do I feel guilty for using ChatGPT to help me draft an email?

Why is a part of me afraid to lose the things that 'make me human'?

It's no surprise our attention spans have diminished.

I tried looking at it from an objective lens and asked "Why is it bad?"

"Why do we resist?"

"Is it really bad?"

Yeah for now.

But what if this is what we are meant to be?

What if the future is going to us living in the 60 second clip format? What if that is the norm?

Sounds a little too dystopian, maybe?

What can we do about it?

We are a freight train running full speed with no guard rails with no intention of stopping. Call it an arms race to development of AGI or call it whatever, one thing is clear - we won't stop working on AI.

Maybe we will crack the code in our lifetimes. Or maybe it's something we will never be able to decipher.

WE are caught in limbo?

So as kids these days will call, "Chat, are we cooked?" (If there is one phrase that I am really digging from this Gen Alpha dictionary, it has to be this one. an I make a quick confession: this is by far one of my favorite things to say these days. I almost find myself giggling when I utter these four words. )

Are we cooked?

Why do we value being a human?

What it takes to be a human?

The good news is everyone has different reasons. That in tself is a 'meta-value'.

I value.

We value.

It got me thinking.

‘Brain rot’ named Oxford Word of the Year 2024

https://www.reddit.com/r/Millennials/comments/1ewudfm/its_just_so_exhausting_what_are_some_words_youve/

https://arxiv.org/abs/2506.08872

<p align="center">

<iframe width="560" height="315" src="https://www.youtube.com/embed/iP_d-tWQTJ4?si=OW0VLLPOfVKHvdI0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

</p>

Think about it this way

1)  Event X happens

2)  Event gets recorded by someone

Sounds pretty straightforward, right? Except it's not.

Let's say I try to recall everything that happened on June 21, 2015. That in itself is something hard to do. I will first have to be like "How old was it was in 2015?

"Where was I in 2015?

"Who was there with me?"

Already my memory is starting to failing on me. I may be able to recall some of the facts that transpired that day, but everything else my brain will literally fill in the blanks - some of it maybe complete fabrication of details or I may straight up omit it.

Even if I were to jot it down and preserve it in a time capsule so that someone from the future were to read about it (not that I expect anyone to do this in the future but you never know); they will literally have to take my word for it (unless of course humanity comes up with a technology to figure out a way to validate historical event. I think the word I am looking for is a time machine.)

Now imagine if my brother was tasked with the same assignment - "Describe everything that happened to Aryamik on June 21, 2015." This further adds more complexities. We are basically asking another individual to describe the events from my point of view. If I can't accurately describe what happened 10 years ago, how can I expect someone else to describe MY POINT OF VIEW? This is the classic theme between autobiographies and biographies comes in.

I genuinely think we as a society owe a debt to the biographers who went this process of conveying the facts.

Think of the burden of responsibility they have.

After all, "history is written by victors."

Think about it. Everything we now consider as 'facts' were at one point in time recorded as texts in some archaic language.

And this is all before translations come in. Imagine trying to convey events of June 21, 2015 in Danish?

Languages are so nuanced and are rapidly evolving. The original event happened in a point in time in history. So already we have a disconnect between the two.

Almost all languages have their unique set of grammatical rules, vocabulary, lexicons, syntax. But these rules are not enough. Context is equally important when it comes to languages. This includes cultural, historical and societal norms of the period when a given text was written. This background information is crucial for accurately intepreting idiomatic expressions, metaphors and references that may not have direct equivalents in modern languages.

It's part of the reason why the idea of solely relying on "Google Translate" when travelling in a foreign country is a bit clunky. Yes AI, can translate the exact words but without the context it just feels...weird.

It is rarely a 1:1 translation.

ble to decipher the grammar, syntax, and vocabulary, often using reference materials like dictionaries, lexicons, and gramm

DFiogenes wrote it one way. Then Yonge translated it in

And then I am trying to make sense out of it in 21st century.

Biographer

We stray further away from the actual event and before we know it, we have a lot of 'noise'

Proficiency in the Source Language

The first and most fundamental skill required for translating ancient texts is a deep understanding of the source language. Ancient languages like Latin, Classical Greek, Sanskrit, or Cuneiform scripts require years of study and practice to master. Translators must be able to decipher the grammar, syntax, and vocabulary, often using reference materials like dictionaries, lexicons, and grammatical guides specific to the ancient language.

Contextual Knowledge

Language alone is not sufficient. Translators must also possess extensive contextual knowledge of the culture, history, and social norms of the period in which the text was written. This background information is crucial for accurately interpreting idiomatic expressions, metaphors, and references that may not have direct equivalents in modern languages.

Paleography and Codicology

Paleography is the study of ancient scripts and handwriting, while codicology focuses on the physical aspects of manuscripts, such as their materials, structure, and layout. Translators must be skilled in both disciplines to properly analyze and interpret ancient texts. Understanding the physicality of a manuscript can offer clues to the context and authorship of the text.

Historical Linguistics

Translating ancient texts often involves dealing with linguistic changes and evolutions. Expertise in historical linguistics is essential for recognizing how languages have transformed over time and identifying archaic or obscure terms that may not appear in standard dictionaries.

But I do hope that future generations look down

There is the other argument

On creativity and AI, Rick Rubin talks about how AI is not stealing creativity but is rather supercharging it.

The way he described it was if we tell AI to go do a thing, we are expecting it to produce something based on how we are envisioning the output. However, more often that not, AI tends to produce stuff that is sorta what we were hoping for but then it also adds its own flair that we couldn't had imagined.

argument is

Trust me I am not a video games apologist and I am not advocating for playing games 12 hours a day (unless you are a pro). But then again, when has too much of anything resulted in anything good?

It shouldn't be video games are the incarnation of evil. Rather the message should be video games do serve a purpose in our life and just like everything else we should be diligent with how we use them.
